/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AllEvent extends javax.swing.JFrame {

    /**
     * Creates new form AllEvent
     */
    public AllEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ButtonClickMe = new javax.swing.JButton();
        TextFieldName = new javax.swing.JTextField();
        TextFieldAge = new javax.swing.JTextField();
        ComboBoxRound = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonClickMe.setText("Click here");
        ButtonClickMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClickMeActionPerformed(evt);
            }
        });

        TextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldNameKeyTyped(evt);
            }
        });

        TextFieldAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldAgeMouseClicked(evt);
            }
        });

        ComboBoxRound.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select A Round", "Round-36", "Round-37", "Round-38" }));
        ComboBoxRound.setToolTipText("Select A Rround\nRound-36\nRound-37\nRound-38");
        ComboBoxRound.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxRoundItemStateChanged(evt);
            }
        });
        ComboBoxRound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxRoundActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonClickMe)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextFieldAge, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                        .addComponent(TextFieldName))
                    .addComponent(ComboBoxRound, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonClickMe)
                    .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TextFieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ComboBoxRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        ComboBoxRound.getAccessibleContext().setAccessibleName("Select A Round\nRound-36\nRound-37\nRound-38");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonClickMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClickMeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Yes! you hit me");
    }//GEN-LAST:event_ButtonClickMeActionPerformed

    private void TextFieldNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldNameKeyTyped
        // TODO add your handling code here:
        if(TextFieldName.getText().length() < 1){
            JOptionPane.showMessageDialog(null, "Enter some text");
        }
    }//GEN-LAST:event_TextFieldNameKeyTyped

    private void TextFieldAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldAgeMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Enter age!");
    }//GEN-LAST:event_TextFieldAgeMouseClicked

    private void ComboBoxRoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxRoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxRoundActionPerformed

    private void ComboBoxRoundItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxRoundItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ComboBoxRoundItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClickMe;
    private javax.swing.JComboBox<String> ComboBoxRound;
    private javax.swing.JTextField TextFieldAge;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
